version: '3'

networks: 
    production-network:

services: 
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx.dockerfile
        image: taironed/nginx
        container_name: nginx
        ports: 
            - "80:80"
        networks: 
            - production-network
        depends_on: 
            - node1
            - node2
            - node3
    
    mongodb:
        image: mongo
        networks: 
            - production-network
    
    node1:
        build: 
            context: .
            dockerfile: ./docker/alura-books.dockerfile
        image: taironed/alura-books
        container_name: alura-books-1
        ports: 
            - "3000"
        networks:
            - production-network
        depends_on: 
            - mongodb
    
    node2:
        build: 
            context: .
            dockerfile: ./docker/alura-books.dockerfile
        image: taironed/alura-books
        container_name: alura-books-2
        ports: 
            - "3000"
        networks:
            - production-network
        depends_on: 
            - mongodb
            
    node3:
        build: 
            context: .
            dockerfile: ./docker/alura-books.dockerfile
        image: taironed/alura-books
        container_name: alura-books-3
        ports: 
            - "3000"
        networks:
            - production-network
        depends_on: 
            - mongodb
            